### ISSUE TITLE
Migration fails for Postgres

### ISSUE THREAD

**Issue by acehead** [Dolphiq/craft3-plugin-redirect#11]
![image](https://user-images.githubusercontent.com/2222878/31434825-35c89f3a-ae86-11e7-8f2e-50045f2d82a9.png)

To fix this issue you need to change line 347 of Redirect.php to this:

`->delete('{{%elements_sites}}', '"elementId" = :elementId AND "siteId" != :siteId', [':elementId' => $record->id, ':siteId' => $this->siteId])`

**Comment by johanzandstra** [comment]
Thank you for your report, I fixed this with the line you posted the fix will be merged later today
