### ISSUE TITLE
"Invalid datetime format" when adding a new redirect

### ISSUE THREAD

**Issue by iparr** [Dolphiq/craft3-plugin-redirect#13]
Please see the attached screenshot.

This happens across two of my environments with Craft CMS 3.0.0-beta.29

Install went fine. Any other details I can provide, please let me know.

![screen shot 2017-10-19 at 10 26 08](https://user-images.githubusercontent.com/497635/31764133-3482e01c-b4b8-11e7-9d8b-8c88fc3b4741.png)

**Comment by johanzandstra** [comment]
Hi, Can you please let me know the Database type/driver and version you are using?

And please try to to change the following in the file:
[craft main path]**/Vendors/dolphiq/redirect/src/elements/Redirect.php**
starting on line: **344**

` 
        Craft::$app->getDb()->createCommand()
            ->delete('{{%elements_sites}}', '"elementId" = :elementId AND "siteId" != :siteId', [':elementId' => $record->id, ':siteId' => $this->siteId])
            ->execute();`

to: 

`
        Craft::$app->getDb()->createCommand()
            ->delete('{{%elements_sites}}', [
                'AND',
                ['elementId' => $record->id],
                ['!=', 'siteId', $this->siteId]
            ])
            ->execute();`

**Comment by iparr** [comment]
**MySQL 5.7.19-0ubuntu0.16.04.1**

I've changed that line and the results are good!

No error message, plus the redirect works and the traffic is recorded.

**Comment by johanzandstra** [comment]
Oke, Thanks for your reply!  We have merged the change to a new minor version and the plugin will work after an update.

**Comment by iparr** [comment]
Thanks @johanzandstra 

Looking at this commit 26c706c - is it possible that you did not apply the change to the new version? I've updated and it remains broken.

**Comment by johanzandstra** [comment]
You are so right @iparr,
I committed the fix but in the next commit it was un-commited.. 

I released a new minor version with the fix. Please let me know if you still having troubles with the new version.

**Comment by iparr** [comment]
Cheers.

I get an error if trying to update via the Dashboard:

> Problem 1 - The requested package dolphiq/redirect 1.0.7 exists as dolphiq/redirect[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, dev-development, dev-master] but these are rejected by your constraint.

I don't know if this is a Composer updating itself thing I need to wait out, or if I've just lost the plot again, or if you need to update the `composter.json` yourself to reflect the new version number? Sorry!
