### ISSUE TITLE
Validate custom fields property no longer present in newest beta

### ISSUE THREAD

**Issue by szczups** [Dolphiq/craft3-plugin-redirect#17]
Hi @johanzandstra, 

Redirect plugin no longer works with newest beta of craft due to the fact that was removed. That's the exception I'm getting: 

`Setting unknown property: dolphiq\redirect\elements\Redirect::validateCustomFields`

Thanks! And let me say - great job!

**Comment by johanzandstra** [comment]
Thanks for reporting this! 

Please let me know if this exception is fixed with the just released update

**Comment by szczups** [comment]
@johanzandstra thanks! That's exactly what was needed. 

Kudos!
