### ISSUE TITLE
Database Exception when adding redirect

### ISSUE THREAD

**Issue by michalochman** [Dolphiq/craft3-plugin-redirect#2]
Hi, it's not possible to add new redirects after adding `hitCount` support.

[`hitCount` field is `NOT NULL`](https://github.com/Dolphiq/craft3-plugin-redirect/commit/5dff2a78c712e7dc39e9ac811d6d0bf15851ea73#diff-eb4ab0584b5426ababdb84f2ffadf519R53) so it probably should have default value of 0.

```SQLSTATE[HY000]: General error: 1364 Field 'hitCount' doesn't have a default value
The SQL being executed was: INSERT INTO `dolphiq_redirects` (`sourceUrl`, `destinationUrl`, `statusCode`, `dateCreated`, `uid`, `dateUpdated`) VALUES ('legal', 'legal/privacy', '302', '2017-07-07 09:45:19', '207a0731-eefe-451e-a15d-ee10270f2ca2', '2017-07-07 09:45:19')
Error Info: Array
(
    [0] => HY000
    [1] => 1364
    [2] => Field 'hitCount' doesn't have a default value
)
↵
Caused by: PDOException

SQLSTATE[HY000]: General error: 1364 Field 'hitCount' doesn't have a default value

in vendor/yiisoft/yii2/db/Command.php at line 846```

**Comment by johanzandstra** [comment]
Thank you for reporting the issue. 
Could you please report the database engine / version you are using?

The plugin is updated. In the update we have added a migration script to set the default DB value for  the column. 

Please run composer update dolphiq/redirect to update the plugin.

**Comment by michalochman** [comment]
I was using MySQL 5.7.18 when this exception was raised. Thanks for fixing! It works after update, however this exception is still raised when the plugin is installed for the first time:

```SQLSTATE[HY000]: General error: 1364 Field 'hitCount' doesn't have a default value The SQL being executed was: INSERT INTO dolphiq_redirects (sourceUrl, destinationUrl, statusCode, dateCreated, uid, dateUpdated) VALUES ('legal', 'legal/privacy', '302', '2017-07-08 09:35:14', '9e9cf9f2-abee-416f-a882-e4b01d90d2fd', '2017-07-08 09:35:14')```
