### ISSUE TITLE
Hard-Coded Table Name Causing Error

### ISSUE THREAD

**Issue by mzlock** [Dolphiq/craft3-plugin-redirect#23]
https://github.com/Dolphiq/craft3-plugin-redirect/blob/master/src/services/Redirects.php#L107

This should be:
```{{%dolphiq_redirects}}```

Right now it's looking for the table `dolphiq_redirects` specifically without considering table prefix settings. This causes an Internal Server Error because it can't find the table.

**Comment by johanzandstra** [comment]
Thanks!, we will change this in the next release

**Comment by johanzandstra** [comment]
#24 just fixed it, thanks again
