### ISSUE TITLE
Error in CP Section When Loading Redirects

### ISSUE THREAD

**Issue by mzlock** [Dolphiq/craft3-plugin-redirect#25]
Related to https://github.com/Dolphiq/craft3-plugin-redirect/issues/23

Changes in 1.0.11 now break functionality in the admin. To clarify my issue in #23 - the admin panel worked great with the existing code. I only got an error when the hit count was updated in `registerHitById`

**Comment by johanzandstra** [comment]
@mzlock what type of db set-up are you using?
I revert part of the commit, can you please try to update to the last master branch?

composer require dolphiq/redirect:dev-master

**Comment by mzlock** [comment]
@johanzandstra - the new version is working for me.

As for database set-up, I'm following the nystudio's .env set-up to start: https://nystudio107.com/blog/multi-environment-config-for-craft-cms

I think the only relevant server setting is I do have a `tablePrefix` set. I'm not really doing anything out-of the ordinary. In `db.php`, I have:
```
'*' => array(
        'tablePrefix' => 'prefixHere'
)
```

I think Craft's `ElementQuery` which you're extending for your `RedirectQuery` is doing you the favor of factoring in the prefix already. The query in your Redirects service, however, is just straight Yii.

**Comment by johanzandstra** [comment]
thanks for your information! 
I have moved the 1.0.11 release version to the new pull request. Next release should be fine with the prefix!
