### ISSUE TITLE
FR: CSV Import/Export?

### ISSUE THREAD

**Issue by Bshally** [Dolphiq/craft3-plugin-redirect#27]
I plan on using this plugin on a future project. It would be great to be able to import/export redirects via a .csv file.

**Comment by johanzandstra** [comment]
Hi @Bshally, 
Nice feature request! I Will put it on the roadmap!

**Comment by azazelA** [comment]
@johanzandstra I've almost 20k urls that need to be redirected. Is it possible to import a csv or do a bulk import directly to the database? I'm using PostgreSQL on craft3.

**Comment by jooplaan** [comment]
We are currently migrating to a CraftCMS website and have many redirects to enter. What would be the correct SQL to add redirects directly to the database?@johanzandstra

**Comment by darylknight** [comment]
+1. Adding redirects to a new site build by hand is a massive pain. Import would be awesome!

**Comment by nfourtythree** [comment]
If anyone happens upon this issue looking for an easy way to import. If you haven't got many to do, you can do a quick bit of copy/pasting/reformatting from a CSV to the following twig template:

```twig
{% set redirects = [
  {src: 'example-src', dest: 'example-dest', type: '301',},
  {src: 'example-src2', dest: 'example-dest2', type: '301',},
] %}

{% for redirect in redirects %}
  {% do craft.app.view.evaluateDynamicContent('
    $entry = new \\dolphiq\\redirect\\elements\\Redirect();
    $entry->sourceUrl = "' ~ redirect.src ~ '";
    $entry->destinationUrl = "' ~ redirect.dest ~ '";
    $entry->statusCode = "' ~ redirect.type ~ '";
  
    Craft::$app->elements->saveElement($entry);
  ')%}
{% endfor %}
```

Call it something e.g. `import` and run it in via the URL. Saves writing a custom plugin/module and east to use as a one off
