### ISSUE TITLE
Twig Error

### ISSUE THREAD

**Issue by marionnewlevant** [Dolphiq/craft3-plugin-redirect#32]
I get this error:
>Twig Syntax Error – Twig_Error_Syntax
> A template that extends another one cannot include contents outside Twig blocks. Did you forget to put the contents inside a {% block %} tag?
> 1. in /home/vagrant/exterro/exterro.com/craft3/craft/vendor/dolphiq/redirect/src/templates/dashboard.twig

When I edit a redirect, and then try to go back to /admin/settings/redirect.

**Comment by johanzandstra** [comment]
@marionnewlevant thank you for reporting the error. Should be fixed in #34
