### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by d13creative** [Dolphiq/craft3-plugin-redirect#33]
Craft 3.0.0-RC7

When trying to install the plugin on the plugins page in settings the error "Cannot use craft\base\Object because 'Object' is a special class name occurs. See screenshot

<img width="1358" alt="screen shot 2018-01-24 at 14 22 34" src="https://user-images.githubusercontent.com/1433528/35338112-e84f891c-0114-11e8-9495-a0ebee5127b5.png">

**Comment by petemcbide** [comment]
I got this error too. Works fine on my localhost, just not on the live server.

**Comment by johanzandstra** [comment]
@d13creative  thank you for reporting the error. Can you please confirm if the error is fixed with the new release #34 ? Thank you!

**Comment by d13creative** [comment]
Yes, works perfectly now, thank you!
