### ISSUE TITLE
Use of Regex

### ISSUE THREAD

**Issue by jondialpad** [Dolphiq/craft3-plugin-redirect#35]
I am wondering if the ability to use regex is in the plans for this plugin. It would be nice just to be able to set up a redirect something like this:

oldpage/?abc=123&apple=pear => http://othersite.com/newpage/?abc=123&apple=pear
or
oldpage/[anything_here] => http://othersite.com/[anything_here] 

I apologize If this is already in place, but I can't seem to find in the documentation.

**Comment by lukeyouell** [comment]
@jondialpad I think you can use `<options:.+>`

`oldpage/<options:.+>`
to
`http://othersite.com/<options>`

**Comment by johanzandstra** [comment]
Please visit the rules page for more info about the available rules
https://github.com/Dolphiq/craft3-plugin-redirect/blob/master/RULES.md

I think you are looking for: 

### Replace a uri parameter in de source string to a new path

Source URL:
```
books/detail
```
Destination URL:
```
book-detail/<bookId>/index.html
```

Example: the original url looks like:
```
books/detail?bookId=124
```

After the redirect, the url will look like:
```
book-detail/124/index.html
```

**Comment by jondialpad** [comment]
Ok, thank you guys I'll try the options 👍
