### ISSUE TITLE
Template not found

### ISSUE THREAD

**Issue by GuidoNeele** [Dolphiq/craft3-plugin-redirect#37]
After installing the plug-in for Craft CMS 3.0.0.RC11 I can't access the redirect and settings page. For both pages I get an 'template not found' exception.
<img width="309" alt="2018-02-21 14_26_40-pagina niet gevonden - crisisconnect" src="https://user-images.githubusercontent.com/1301586/36482497-c6a43212-1713-11e8-8461-577a304bc74e.png">

**Comment by ddbr** [comment]
Same here!

**Comment by m8i** [comment]
Same here

**Comment by johanzandstra** [comment]
this is related to a change in the core of Craft:
Removed the registerCpRoutes and registerSiteRoutes plugin hooks. Custom URL rules for the Control Panel and front-end site should be registered using the registerCpUrlRules and registerSiteUrlRules events on craft\web\UrlManager now.

fixing it right now

**Comment by ddbr** [comment]
Hi Johan

Same issue in your sitemap plugin. thanks a lot!

Daniel

**Comment by johanzandstra** [comment]
@GuidoNeele, @ddbr, @m8i 
should be fixed in v1.0.15

**Comment by ddbr** [comment]
Thanks works with v1.0.15!

**Comment by GuidoNeele** [comment]
Problem solved! Thanks
