### ISSUE TITLE
Craft 3 - Redirect from a URL that resolves not working

### ISSUE THREAD

**Issue by jasonmckinney66** [Dolphiq/craft3-plugin-redirect#39]
Trying to redirect from a parent page to first child. Both urls resolve. The redirect does not work. 
But, if the original source does not exist, the redirect works. Is this the intended functionality? In other words, must the source URL not exist within the site?

**Comment by johanzandstra** [comment]
That is correct. The craft3 route lifecycle is described here:
https://github.com/craftcms/docs/blob/v3/en/routing.md
The plugin will handle requests in step 3. Before that, the requests go to existing enties an categories. If you want to re-route the requests of existing entries, you should configure it with server rewrite rules in the server config or .htaccess file.

**Comment by grafixgeek** [comment]
Could the ability to redirect existing pages be added as a feature request? The case in point - redirecting parent to first (or any child) is my most common use and what I used Reroute in Craft 2 (not upgraded to v3). Content editors need to be able to do this so server rewrite rules are not really accessible for them.
