### ISSUE TITLE
Fresh install: The table does not exist: {{%dolphiq_redirects_catch_all_urls}}

### ISSUE THREAD

**Issue by matt-adigital** [Dolphiq/craft3-plugin-redirect#42]
Craft CMS 3.0.0-RC17.1
Redirect plugin for Craft 3 1.0.15

I've just downloaded and installed this plugin and added a few redirects. It works great! I then however went and turned on the "Use a Catch All page template" setting, I've set a 404 template but I keep getting the error The table does not exist: {{%dolphiq_redirects_catch_all_urls}} on the front end.

When I go to "Registered catch all urls" in the CP I get the following message:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sitename_db.dolphiq_redirects_catch_all_urls' doesn't exist
The SQL being executed was: SELECT *
FROM `dolphiq_redirects_catch_all_urls`
WHERE `siteId`=1
ORDER BY `dateUpdated` DESC
LIMIT 100

Error Info: Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'sitename_db.dolphiq_redirects_catch_all_urls' doesn't exist
)

I had a look at the plugin files and can see that this table was added in a migration file as part of a previous update but the Install.php file doesn't reference these tables. My guess would be that the Install file needs to have the new tables in aswell as having them defined in the migrations folder because it looks like it hasn't created the tables when I've installed the plugin. Could this be looked into so I can use this for redirecting to a 404 page please? Thank you.

**Comment by johanzandstra** [comment]
@matt-adigital, thanks for reporting this issue. this should have worked in the past but we will change this in the new version.

**Comment by mike-rotate** [comment]
currently having this issue with :

Craft CMS 3.0.7 & Redirect plugin for Craft 3 1.0.16

**Comment by LukePeters** [comment]
Was this bug ever fixed? I'm using this plugin and running into the exact same error on Craft 3.0.34. Thank you!

**Comment by diegovogel** [comment]
Same issue here. Craft 3.3.16.3 and Redirect Manager 1.0.23. @johanzandstra was this problem ever fixed?

**Comment by TikiKitchen** [comment]
This bug is still occurring. How can it be fixed?
