### ISSUE TITLE
Underscore next to icon in sidebar

### ISSUE THREAD

**Issue by Coysh** [Dolphiq/craft3-plugin-redirect#45]
For some weird reason, there is an underscore next to the icon on the sidebar. All the other plugin icon display correctly.

![image](https://user-images.githubusercontent.com/5764356/39045618-3d9217c8-448b-11e8-87ee-dfb05e5ed6f8.png)

**Comment by Coysh** [comment]
@RichardFrontwise see you made a change, but I'm on `dev-master` and the change hasn't come through?

**Comment by lukebailey** [comment]
Currently I see no icon on the sidebar - running version 1.0.16

![image](https://user-images.githubusercontent.com/3185073/40057524-6b8f2ef8-5846-11e8-8687-13e8ebb7c94d.png)

**Comment by RichardFrontwise** [comment]
In Craft 'icon' changed to 'fontIcon', check my pull request: https://github.com/Dolphiq/craft3-plugin-redirect/pull/48

**Comment by johanzandstra** [comment]
@Coysh thanks! the Underscore was there for a reason ;) (i kind of liked it.. ) but the new version of Craft is working differently with icons, for now I have chosen a new one, I will update the plugin today, feel free to suggest an other!
