### ISSUE TITLE
Ability to set exact matching

### ISSUE THREAD

**Issue by sergeifilippov** [Dolphiq/craft3-plugin-redirect#51]
I have a case where the matching needs to be stricter than currently possible (I looked over the docs and could not see anything that would help).

Scenario:

Website has the following page `/local-mall-info`.

When I setup a redirect for the uri `mall-info` the redirection redirects to `mall-info` with partial content from `local-mall-info` page.

Weird.

**Comment by johanzandstra** [comment]
@sergeifilippov the plugin should match exact, I could no reproduce this if i use /test-123 and /test i go to an other page with the both requests. Dit you use variables in the url's ?

**Comment by sergeifilippov** [comment]
Thanks for having a go. No variables in the urls.

I'll close this for now.
