### ISSUE TITLE
Blacklist or Catch urls without using Catch All

### ISSUE THREAD

**Issue by spAnser** [Dolphiq/craft3-plugin-redirect#54]
So I enabled catch all so that I could get a list of urls that are not being handled.

Now nothing can visit `robots.txt`, `humans.txt` or `sitemap.xml`.

Is there a way to catch 404s while also letting craft handle just serving up the 404 template if it thinks it is needed.

If that is not something that can happen I would love to have a don't catch blacklist option.

**Comment by johanzandstra** [comment]
Please let me know if this is fixed in version 1.0.20
