### ISSUE TITLE
New Redirects Not Working

### ISSUE THREAD

**Issue by jamash** [Dolphiq/craft3-plugin-redirect#58]
Any new redirects setup are not working, but existing ones are still functioning.

**Comment by mariovass** [comment]
This plugin is not working for me - redirects are not working...

**Comment by jamash** [comment]
Resolved this. 

A redirect in Craft's 'routes' config which was preventing the redirect plugin from working. It wasn't doing anything other than breaking stuff; once removed the plugin started working again.
