### ISSUE TITLE
Putting a # into the Source URL Breaks Site

### ISSUE THREAD

**Issue by khamer** [Dolphiq/craft3-plugin-redirect#59]
Ran into this today when a user added a Source URL with an anchor in it. I'd guess somewhere internally '#' is being used to delimit regex expressions for UrlRule, and '#' should be escaped.

**Comment by daniellefrapp** [comment]
I am also having the same issue as well

**Comment by johanzandstra** [comment]
you can’t server-side redirect to the hash part of a link - the hash part is only managed by the client (browser), so while you can generate a link including a hash. In the next version we will allow a # in the source url but it will only match the part before the # character
