### ISSUE TITLE
Number Url causes a UrlRule::pattern Error

### ISSUE THREAD

**Issue by mzlock** [Dolphiq/craft3-plugin-redirect#62]
Version: 1.0.18 (latest)

Steps to reproduce:
- Create a new redirect where the `sourceUrl` is a number. Example: `/2018`
- the `destinationUrl` can be anything
- 301 redirect (but probably would error either way)

Error:
All routes produce this error, stumbling on the number:

Invalid Configuration – yii\base\InvalidConfigException
UrlRule::pattern must be set.

Possible solution:
Make sure all routes are stored to the database as strings. I think the `2018` is being saved as a number and is therefore being parsed as a pattern instead of an exact route.

**Comment by johanzandstra** [comment]
Thanks, I will have a look into this!

**Comment by Coysh** [comment]
Any update on this?

**Comment by johanzandstra** [comment]
@Coysh this should be fixed in the next update
