### ISSUE TITLE
A Few Minor Spelling Issues

### ISSUE THREAD

**Issue by chris-lawrence** [Dolphiq/craft3-plugin-redirect#64]
Thanks for the plugin.  Just spotted a few minor spelling issues.

In the menu: 
Temporarily redirects
Should be: 
Temporary redirects

In Settings:
This switch activate/de-activate all the entered redirects without removing them.
Should be:
This switch activates/de-activates all the entered redirects without removing them.

Also in Settings:
All the not existing urls are redirected to this page. We also register the missed urls.
Should be:
All the non-existing urls are redirected to this page. We also register the missed urls.

Under Registered catch all urls, if you don't have any registered catch alls:
No registered catch url's exist yet.
Should be
No registered catch urls exist yet.

**Comment by johanzandstra** [comment]
Please open a pull request with the requested changes, thanks!
