### ISSUE TITLE
Redirect stopped working, Uninstalled, removed, added, will not reinstall - Couldn’t install plugin.

### ISSUE THREAD

**Issue by butchewing** [Dolphiq/craft3-plugin-redirect#70]
One of my redirects stopped working after the latest Craft update (Craft Pro 3.1.15). The other redirects were working fine. I uninstalled, removed, and then added back the plugin from the Plugin Store. Now the plugin will not install. I get the following message: Couldn’t install plugin.

This is the redirect that was not working:
![screen shot 2019-02-28 at 12 35 26 pm](https://user-images.githubusercontent.com/405072/53596164-c20e5b80-3b64-11e9-9f0a-eb8083ba0857.jpg)

**Comment by johanzandstra** [comment]
Please let me know if you fixed this problem
