### ISSUE TITLE
Latest Version not in Packagist

### ISSUE THREAD

**Issue by adampatpattison** [Dolphiq/craft3-plugin-redirect#78]
Hello, 

https://packagist.org/packages/dolphiq/redirect

Packagist only goes up to version 1.0.9 where as 2.0.7 is the version available in the plugin store.

Our deployment requires all packages updated via composer and we'd like to be on the latest version of your plugin please.

Below is the problem we are getting from composer:

> composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - The requested package dolphiq/redirect 2.0.7 exists as dolphiq/redirect[1.0.0, 1.0.1, 1.0.10, 1.0.11, 1.0.12, 1.0.13, 1.0.14, 1.0.15, 1.0.16, 1.0.17, 1.0.18, 1.0.2, 1.0.20, 1.0.21, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.8, 1.0.9, dev-development, dev-master] but these are rejected by your constraint.

Is there any chance you could update/sync the versions to packagist please.

**Comment by johanzandstra** [comment]
Hi @adampatpattison, 
Thanks for you message. This was caused by a side effect of merging a forked repository into a branch. We have solved this issue. The latest version is: v1.0.21
