### ISSUE TITLE
Class 'verbb\feedme\services\Elements' not found

### ISSUE THREAD

**Issue by superpikar** [Dolphiq/craft3-plugin-redirect#80]
### Description
Hello, an error occured after I update craft3-plugin-redirect and feed me. 
```
Class 'verbb\feedme\services\Elements' not found
```
This error maybe because of ["Craft Acquired FeedMe"](https://craftcms.com/blog/feed-me), so the namescape change from `verbb\feedme` to `craft\feedme`

### Additional info
- Plugin version : 1.0.21
- Craft version: 3.1.23
- PHP version: 7.3
- Other plugins & versions (if applicable): feed-me 4.0.0

**Comment by Mosnar** [comment]
Thanks, this fix should go out in 1.0.22

**Comment by chrisrowe** [comment]
@Mosnar Thanks! Any ETA?

**Comment by johanzandstra** [comment]
@chrisrowe version 1.0.22 is just released
