### ISSUE TITLE
Plugin won't install after last update

### ISSUE THREAD

**Issue by vikdialpad** [Dolphiq/craft3-plugin-redirect#82]
We're seeing any where the plugin is not enabled after we build our Craft site. This started after the last update to the plugin. When trying to enable it we get the following error:

```
db_1        | 2019-04-19 22:31:43.820 UTC [201] ERROR:  relation "dp_dolphiq_redirects" already exists
db_1        | 2019-04-19 22:31:43.820 UTC [201] STATEMENT:  CREATE TABLE "dp_dolphiq_redirects" (
db_1        | 		"id" serial NOT NULL PRIMARY KEY,
db_1        | 		"type" varchar(8) NOT NULL DEFAULT 'static',
db_1        | 		"sourceUrl" varchar(255),
db_1        | 		"destinationUrl" varchar(255),
db_1        | 		"statusCode" varchar(255),
db_1        | 		"hitCount" integer NOT NULL DEFAULT 0,
db_1        | 		"hitAt" timestamp(0),
db_1        | 		"dateCreated" timestamp(0) NOT NULL,
db_1        | 		"dateUpdated" timestamp(0) NOT NULL,
db_1        | 		"dateDeleted" timestamp(0) NULL DEFAULT NULL,
db_1        | 		"uid" char(36) NOT NULL DEFAULT '0'
db_1        | 	)
db_1        | 2019-04-19 22:31:43.828 UTC [201] ERROR:  current transaction is aborted, commands ignored until end of transaction block
```

If we lock in the version of the plugin to v1.0.20 everything remains fine, and the plugin is enabled once we've built the site, and the redirects remain intact.

**Comment by Mosnar** [comment]
There were some erroneous 2.0 releases on packagist. These have been removed. You should be able to safely update now!

**Comment by chasegiunta** [comment]
@Mosnar Even though the plugin is available now, it cannot be reinstalled due to the error above.

**Comment by chasegiunta** [comment]
Just attempted to export those tables, delete them, and then install the plugin. Installed successfully but reinstating the tables breaks the plugin so I'm assuming there's a migration that needs to run.
