### ISSUE TITLE
Time stamp is GMT?

### ISSUE THREAD

**Issue by sam327** [Dolphiq/craft3-plugin-redirect#84]
I've got my site configured to be my local time zone, Eastern / New York, and most things are fine.

But the time stamps in the "last hit" column are all by four hours. So it looks like it's using GMT rather than the local time zone.  

Is this something that needs to be updated in the plugin? Or is there a setting I can add in a config file?

**Comment by johanzandstra** [comment]
The Plugin is currently using a database query now() to update the last hit. I guess your database date settings are set to GMT
