### ISSUE TITLE
Return value of dolphiq\redirect\RedirectPlugin::registerFeedMeElement() must be an instance of dolphiq\redirect\void, none returned

### ISSUE THREAD

**Issue by mofman** [Dolphiq/craft3-plugin-redirect#90]
Return value of dolphiq\redirect\RedirectPlugin::registerFeedMeElement() must be an instance of dolphiq\redirect\void, none returned

**Comment by nilsenpaul** [comment]
We have the same issue. `:void` is not a return type in PHP < 7.1. Removing `:void` from line 145 of RedirectPlugin.php solves the problem.

**Comment by johanzandstra** [comment]
Just fixed this in release v1.0.23
