### ISSUE TITLE
Getting unknown property: dolphiq\redirect\elements\Redirect::plugin

### ISSUE THREAD

**Issue by darylknight** [Dolphiq/craft3-plugin-redirect#92]
When I clone my production database to my local machine, I've started seeing `Getting unknown property: dolphiq\redirect\elements\Redirect::plugin` and I can't access the front end of the site until I disable the plugin (I can access the CP). It doesn't happen when I re-install the plugin, so I think this may be something to do with creating a redirect from something to "/", which then gets removed and turned in to "" when you save the redirect.

Let me know if I can give you any more info!

**Craft CMS 3.1.26
Redirect plugin for Craft 3 1.0.23**

**Comment by tomjrjones** [comment]
@darylknight Have you tried clearing your vendor folder and running `composer install`?

**Comment by darylknight** [comment]
Sorry Tom, this was a couple of months ago and I don't remember which project this was for. If there's no obvious cause, it's probably better to close this for now.
